"""Factual Alignment Engine (FAE) - FAC v1.0 Implementation."""

from fae.api import (
    FactualAlignmentEngine,
    FAEConfig,
    Evidence,
    ProvenanceMetadata,
    EvidenceSource,
    EvidenceStatus,
    FRACycle,
    FRACycleStage,
    CycleContext,
    StageResult,
    FRACycleError,
    FACInvariantViolation,
    ValidationMetricsEngine,
    CycleValidationReport,
    ValidationResult,
    DriftDetectionEngine,
    DriftEvent,
    DriftType,
    DriftSeverity,
    DriftThresholds,
    ConstitutionalStateRecord,
    CycleLog,
    AlignmentCheck,
    create_fae,
    quick_cycle,
    reset_fae,
)

__version__ = "1.0.0"
__all__ = [
    "FactualAlignmentEngine",
    "FAEConfig",
    "Evidence",
    "ProvenanceMetadata",
    "EvidenceSource",
    "EvidenceStatus",
    "FRACycle",
    "FRACycleStage",
    "CycleContext",
    "StageResult",
    "FRACycleError",
    "FACInvariantViolation",
    "ValidationMetricsEngine",
    "CycleValidationReport",
    "ValidationResult",
    "DriftDetectionEngine",
    "DriftEvent",
    "DriftType",
    "DriftSeverity",
    "DriftThresholds",
    "ConstitutionalStateRecord",
    "CycleLog",
    "AlignmentCheck",
    "create_fae",
    "quick_cycle",
    "reset_fae",
]